### ISSUE TITLE
Is it possible to implement "rsync --remove-source-files"

### ISSUE THREAD

**Issue by masan97160852** [elesiuta/backupy#3]
As title, is it possible to implement "rsync --remove-source-files"? It will save lots of steps to handle the source files.

**Comment by elesiuta** [comment]
I'd rather not have to support that feature since it goes against the design goals and would complicate how the databases on each side are managed, which I'm trying to keep as simple as possible.

However it should be possible for you to extend backupy with that feature pretty easily (I have not tested this)
```python
import subprocess
import backupy
def main():
    backupy.fileman.FileManager.copy_function = lambda source, dest: subprocess.run(["rsync", "--archive", "--remove-source-files", source, dest])
    sys.exit(backupy.main())
if __name__ == "__main__":
    sys.exit(main())
```
That script should work, and if you also wanted to install it, save it as `backupy-extended.py` then create the following `setup.py`
```python
import setuptools
setuptools.setup(
    name="backupy-extended",
    version="1.0.0",
    description="A simple backup program in python with an emphasis on data integrity and transparent behaviour",
    long_description="Extended to use rsync --remove-source-files",
    long_description_content_type="text/markdown",
    py_modules=["backupy-extended"],
    entry_points={"console_scripts": ["backupy-extended = backupy-extended:main"]},
)
```
Then install and run it with
```
python setup.py install --user
backupy-extended (you might need to add it to path, or use python -m backupy-extended)
```
It should go without saying that this will only work with backup mode (you'll start losing files after multiple runs if try using it with mirror or sync modes). The removed source files will still show up in the source database until the next run, but that shouldn't matter.

**Comment by elesiuta** [comment]
One other possibility if you want to avoid using rsync and keep the databases up to date with removals, is add this after line 258 here https://github.com/elesiuta/backupy/blob/v1.8.6/backupy/backupman.py#L255
```python
fileman.handleDeletedFiles(self.config.source, source_only)
fileman.handleDeletedFiles(self.config.source, changed)
```

**Comment by masan97160852** [comment]
The second solution looks great to me!! because there is no "native rsync" in windows platform (I know "cwRsync" does, but it needs lots of Cygwin dll support). The solution is the pure python what I'm looking for.
